### PR TITLE
"To:" header 

### PR DESCRIPTION
**Pull request by tommywo**

### CODE REVIEW

**Comment by tommywo** [comment]
One test is failling. I don't know why

--- FAIL: TestRestMessage (2.00s)
	rest_test.go:394: Expected JSON.To="to1", got ""
FAIL
FAIL	github.com/jhillyerd/inbucket/webui	2.014s

**Comment by jhillyerd** [comment]
Hmm, I can't see a reason for that failure.  I'm out of town without a dev environment to play around with right now.

I should mention that I plan on taking care of #28 during 1.2 - since only the code in the `webui` package is failing (and will end up being removed) - you could probably revert the JSON.To stuff you added to the `webui` package.  Only the `rest` package will be used for JSON API going forward.

**Comment by tommywo** [comment]
I did what you said and all tests are passing now. :)

**Comment by jhillyerd** [comment]
Thanks for doing this @tommywo! I am going to play around with this branch, hopefully this weekend.  If things look good I will merge into the main develop branch.

**Pull request merged**
